[greeter]
theme-name = Yaru-red-dark
icon-theme-name = Papirus-Dark
font-name = JetBrains Mono 11
background = /usr/share/backgrounds/whitehatso-login.png
user-background = false
position = 50% 50%
indicators = ~host;~clock;~layout;~session;~power
clock-format = %a %d %b  %H:%M
screensaver-timeout = 60
xft-antialias = true
xft-hintstyle = slight
xft-rgba = rgb
